-- Model-quality/risk-control additions from the 2026-06-08 shadow observations.
-- Keeps production behavior read-only; this only adds audit metadata and counterfactual storage.

alter table public.signals
  add column if not exists raw_forecast_value double precision,
  add column if not exists forecast_sigma double precision,
  add column if not exists model_source text,
  add column if not exists bias_correction double precision,
  add column if not exists bias_correction_n integer,
  add column if not exists bias_mae double precision;

alter table public.shadow_snapshots
  add column if not exists variable text,
  add column if not exists threshold double precision,
  add column if not exists raw_forecast_value double precision,
  add column if not exists forecast_sigma double precision,
  add column if not exists model_source text,
  add column if not exists bias_correction double precision,
  add column if not exists bias_correction_n integer,
  add column if not exists bias_mae double precision;

create table if not exists public.counterfactual_outcomes (
  id bigint generated by default as identity primary key,
  source text not null,
  source_row_id bigint not null,
  ticker text not null,
  selected_side text,
  selected_price_cents double precision,
  fee_cents double precision,
  fee_adjusted_ev_cents double precision,
  skipped_reason text,
  settlement_result text,
  result_value double precision,
  payout_cents double precision,
  counterfactual_pnl_cents double precision,
  settlement_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, source_row_id)
);

create index if not exists idx_counterfactual_source_ticker on public.counterfactual_outcomes(source, ticker);
create index if not exists idx_counterfactual_skipped_reason on public.counterfactual_outcomes(skipped_reason);
create index if not exists idx_counterfactual_pnl on public.counterfactual_outcomes(counterfactual_pnl_cents);
create index if not exists idx_shadow_snapshots_variable_hour on public.shadow_snapshots(variable, target_hour);

alter table public.counterfactual_outcomes enable row level security;
