-- Initial Supabase/Postgres schema for the Kalshi weather bot.
-- Mirrors the current SQLite ledger so a future Postgres Store can write scans,
-- signals, paper/demo orders, production-shadow snapshots/fills, and runner events.

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  market_limit integer not null,
  notes text
);

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  ticker text not null,
  title text not null,
  city text,
  target_date date,
  target_hour integer,
  variable text,
  threshold double precision,
  forecast_value double precision,
  probability_yes double precision,
  fair_yes_cents double precision,
  fair_no_cents double precision,
  yes_bid_cents double precision,
  yes_ask_cents double precision,
  yes_ask_size double precision,
  no_bid_cents double precision,
  no_ask_cents double precision,
  no_ask_size double precision,
  selected_side text,
  selected_price_cents double precision,
  edge_cents double precision,
  fee_cents double precision,
  fee_adjusted_ev_cents double precision,
  skipped_reason text,
  band_lower double precision,
  band_upper double precision,
  event_ticker text,
  lookahead_risk integer,
  created_at timestamptz not null default now()
);

create table if not exists public.paper_orders (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  signal_id bigint not null references public.signals(id) on delete cascade,
  ticker text not null,
  side text not null,
  quantity integer not null,
  limit_price_cents double precision not null,
  avg_fill_price_cents double precision,
  fee_cents double precision,
  status text not null,
  reason text,
  settlement_status text,
  settlement_result text,
  settled_at timestamptz,
  payout_cents double precision,
  realized_pnl_cents double precision,
  settlement_json jsonb,
  result_value double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.paper_positions (
  ticker text not null,
  side text not null default 'BUY_YES',
  quantity integer not null,
  avg_price_cents double precision not null,
  total_fees_cents double precision not null,
  updated_at timestamptz not null default now(),
  primary key (ticker, side)
);

create table if not exists public.demo_orders (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  signal_id bigint not null references public.signals(id) on delete cascade,
  local_order_id bigint references public.paper_orders(id) on delete set null,
  ticker text not null,
  client_order_id text not null,
  kalshi_order_id text,
  side text not null,
  quantity text not null,
  price_dollars text not null,
  status text not null,
  response_json jsonb,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists public.demo_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  balance_json jsonb,
  positions_json jsonb
);

create table if not exists public.shadow_snapshots (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  ticker text not null,
  title text not null,
  city text,
  target_date date,
  target_hour integer,
  market_status text,
  close_time timestamptz,
  production_base_url text,
  forecast_value double precision,
  probability_yes double precision,
  fair_yes_cents double precision,
  fair_no_cents double precision,
  yes_bid_cents double precision,
  yes_ask_cents double precision,
  yes_ask_size double precision,
  no_bid_cents double precision,
  no_ask_cents double precision,
  no_ask_size double precision,
  spread_cents double precision,
  selected_side text,
  selected_price_cents double precision,
  edge_cents double precision,
  fee_cents double precision,
  fee_adjusted_ev_cents double precision,
  skipped_reason text,
  orderbook_json jsonb,
  band_lower double precision,
  band_upper double precision,
  event_ticker text,
  lookahead_risk integer,
  created_at timestamptz not null default now()
);

create table if not exists public.shadow_orders (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.scans(id) on delete cascade,
  snapshot_id bigint not null references public.shadow_snapshots(id) on delete cascade,
  ticker text not null,
  side text not null,
  quantity integer not null,
  limit_price_cents double precision not null,
  avg_fill_price_cents double precision,
  fee_cents double precision,
  status text not null,
  reason text,
  settlement_status text,
  settlement_result text,
  settled_at timestamptz,
  payout_cents double precision,
  realized_pnl_cents double precision,
  settlement_json jsonb,
  result_value double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.runner_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  level text not null,
  message text not null
);

-- Read/query indexes used by dashboard, calibration, settlement, and safety checks.
create index if not exists idx_signals_scan_id on public.signals(scan_id);
create index if not exists idx_signals_ticker on public.signals(ticker);
create index if not exists idx_signals_event_ticker on public.signals(event_ticker);
create index if not exists idx_signals_created_at on public.signals(created_at desc);
create index if not exists idx_signals_skipped_reason on public.signals(skipped_reason);

create index if not exists idx_paper_orders_scan_id on public.paper_orders(scan_id);
create index if not exists idx_paper_orders_signal_id on public.paper_orders(signal_id);
create index if not exists idx_paper_orders_ticker on public.paper_orders(ticker);
create index if not exists idx_paper_orders_status_unsettled on public.paper_orders(status, realized_pnl_cents);
create index if not exists idx_paper_orders_created_at on public.paper_orders(created_at desc);

create index if not exists idx_demo_orders_scan_id on public.demo_orders(scan_id);
create index if not exists idx_demo_orders_local_order_id on public.demo_orders(local_order_id);
create index if not exists idx_demo_orders_created_at on public.demo_orders(created_at desc);

create index if not exists idx_shadow_snapshots_scan_id on public.shadow_snapshots(scan_id);
create index if not exists idx_shadow_snapshots_ticker on public.shadow_snapshots(ticker);
create index if not exists idx_shadow_snapshots_event_ticker on public.shadow_snapshots(event_ticker);
create index if not exists idx_shadow_snapshots_created_at on public.shadow_snapshots(created_at desc);
create index if not exists idx_shadow_snapshots_skipped_reason on public.shadow_snapshots(skipped_reason);

create index if not exists idx_shadow_orders_scan_id on public.shadow_orders(scan_id);
create index if not exists idx_shadow_orders_snapshot_id on public.shadow_orders(snapshot_id);
create index if not exists idx_shadow_orders_ticker on public.shadow_orders(ticker);
create index if not exists idx_shadow_orders_status_unsettled on public.shadow_orders(status, realized_pnl_cents);
create index if not exists idx_shadow_orders_created_at on public.shadow_orders(created_at desc);

create index if not exists idx_runner_events_created_at on public.runner_events(created_at desc);
create index if not exists idx_runner_events_level on public.runner_events(level);

-- Keep the project private by default. Backend services should use the service role
-- key or direct Postgres credentials. Add explicit read-only policies later if a
-- public/anon dashboard is desired.
alter table public.scans enable row level security;
alter table public.signals enable row level security;
alter table public.paper_orders enable row level security;
alter table public.paper_positions enable row level security;
alter table public.demo_orders enable row level security;
alter table public.demo_snapshots enable row level security;
alter table public.shadow_snapshots enable row level security;
alter table public.shadow_orders enable row level security;
alter table public.runner_events enable row level security;
